# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guiIRRDN.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1261, 916)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setAutoFillBackground(False)
        self.pushButton_7.setCheckable(False)
        self.pushButton_7.setDefault(False)
        self.pushButton_7.setFlat(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_4.addWidget(self.pushButton_7)
        self.RegisterUserButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RegisterUserButton.sizePolicy().hasHeightForWidth())
        self.RegisterUserButton.setSizePolicy(sizePolicy)
        self.RegisterUserButton.setObjectName("RegisterUserButton")
        self.verticalLayout_4.addWidget(self.RegisterUserButton)
        self.VerifyUserButton = QtWidgets.QPushButton(self.centralwidget)
        self.VerifyUserButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VerifyUserButton.sizePolicy().hasHeightForWidth())
        self.VerifyUserButton.setSizePolicy(sizePolicy)
        self.VerifyUserButton.setObjectName("VerifyUserButton")
        self.verticalLayout_4.addWidget(self.VerifyUserButton)
        self.ShowRegisteredUsers = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ShowRegisteredUsers.sizePolicy().hasHeightForWidth())
        self.ShowRegisteredUsers.setSizePolicy(sizePolicy)
        self.ShowRegisteredUsers.setObjectName("ShowRegisteredUsers")
        self.verticalLayout_4.addWidget(self.ShowRegisteredUsers)
        self.CloseProgramButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CloseProgramButton.sizePolicy().hasHeightForWidth())
        self.CloseProgramButton.setSizePolicy(sizePolicy)
        self.CloseProgramButton.setObjectName("CloseProgramButton")
        self.verticalLayout_4.addWidget(self.CloseProgramButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(0, -1, -1, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.statusPrompt = QtWidgets.QPushButton(self.centralwidget)
        self.statusPrompt.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusPrompt.sizePolicy().hasHeightForWidth())
        self.statusPrompt.setSizePolicy(sizePolicy)
        self.statusPrompt.setCheckable(False)
        self.statusPrompt.setAutoDefault(False)
        self.statusPrompt.setDefault(False)
        self.statusPrompt.setFlat(False)
        self.statusPrompt.setObjectName("statusPrompt")
        self.gridLayout_3.addWidget(self.statusPrompt, 4, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("bgLabel.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 4, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("bgLabel.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 1, 2, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("bgLabel.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 1, 2, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionClose_2 = QtWidgets.QAction(MainWindow)
        self.actionClose_2.setObjectName("actionClose_2")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setShortcutVisibleInContextMenu(False)
        self.actionAbout.setObjectName("actionAbout")
        self.actionRegister = QtWidgets.QAction(MainWindow)
        self.actionRegister.setObjectName("actionRegister")
        self.actionVerify = QtWidgets.QAction(MainWindow)
        self.actionVerify.setObjectName("actionVerify")
        self.actionShow_All = QtWidgets.QAction(MainWindow)
        self.actionShow_All.setObjectName("actionShow_All")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Iris Recognition Registration Database"))
        self.pushButton.setText(_translate("MainWindow", "Iris Registered Database"))
        self.pushButton_7.setText(_translate("MainWindow", "Registered ID: XXXXXXX"))
        self.RegisterUserButton.setText(_translate("MainWindow", "Register User"))
        self.VerifyUserButton.setText(_translate("MainWindow", "Verify User"))
        self.ShowRegisteredUsers.setText(_translate("MainWindow", "Show Registered Users"))
        self.CloseProgramButton.setText(_translate("MainWindow", "Close"))
        self.statusPrompt.setText(_translate("MainWindow", "Registered. OK."))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionClose_2.setText(_translate("MainWindow", "Close"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionRegister.setText(_translate("MainWindow", "Register"))
        self.actionVerify.setText(_translate("MainWindow", "Verify"))
        self.actionShow_All.setText(_translate("MainWindow", "Show All"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
